### ISSUE TITLE
[Question] Why action icon color isn't white in a dark theme?  

### ISSUE THREAD

**Issue by ceyhunnabiyev** [gusbemacbe/suru-plus#56]
![screenshot from 2018-10-19 21-16-32](https://user-images.githubusercontent.com/5506156/47233589-4a753680-d3e4-11e8-9548-1e1868a9c33f.png)

 Active action icon doesn't differ from disabled one:
![screenshot from 2018-10-19 21-18-22](https://user-images.githubusercontent.com/5506156/47233773-d25b4080-d3e4-11e8-80e2-2c2f83e3a59a.png)

**Comment by gusbemacbe** [comment]
Hi @ceyhunnabiyev !

This icons theme is not for dark environments, but when it will be ready, I will integrate into [Suru++ Dark](https://github.com/gusbemacbe/suru-plus-dark) and upgrade. Observe that Suru++ Dark is too outdated.

I worked hard during 4 months, fixing this icons theme because the original author messed everything.

**Comment by ceyhunnabiyev** [comment]
Hi @gusbemacbe , Thanks for answer. Some icon color is white, some is grey, that is why  I asked..

> I worked hard during 4 months, fixing this icons theme because the original author messed everything.

Ok, no problem, just wait. I love your work.

**Comment by gusbemacbe** [comment]
Hi @ceyhunnabiyev !


I inform you that [Suru++ Dark](/gusbemacbe/suru-plus-dark) has been upgraded and renamed to Suru++ 25 Dark. Check the screenshots: https://www.opendesktop.org/p/1245808/.
