### ISSUE TITLE
Full trash icon issue in KDE Plasma

### ISSUE THREAD

**Issue by aburke161** [gusbemacbe/suru-plus#73]
The "edittrash.svg" icon doesn't render correctly in KDE Plasma 5.14. It seems that the clipping is being ignored? The paper inside of the bin is rendered on the top layer. I'm not sure if this is a problem with the theme or how Plasma itself renders svg files. However, it renders correctly in Firefox as well as Inkscape so I figure this is a good place to start. Attached is a screenshot of how it is rendered. 
![trashicon](https://user-images.githubusercontent.com/44245956/49900618-07a46d80-fe2d-11e8-94b4-0c6bc3b5c140.png)

**Comment by gusbemacbe** [comment]
Hi @aburke161 !

It is one of the known issues by me. 

As I am done with the college and got graduated, I will begin to review the Suru++ 20 and upgrade the new version, _papirusise_ the icons to end up with all the bugs.

**Comment by aburke161** [comment]
Hey @gusbemacbe (: 

Ah okay, that's good to know. I was worried it was something specific to my system since I couldn't find anyone talking about it. Congratulations on graduating! This is a gorgeous theme, by the way.

**Comment by gusbemacbe** [comment]
Thank you, @aburke161 ! Observe that I use KDE as the main OS for testing SVG icons if they look good, but I was unaware that the original trash icon was not fixed. I had acknowledge of this icon. The original author of Suru++ uses GTK as the main OS and did not test the icons in KDE or can not test because he is not a system analysist or programmer, so I assume his place. I am co-creator and contributor of his original icons theme [Suru++](https://github.com/Magog64/suru-plus), which does not support KDE.

**Comment by gusbemacbe** [comment]
@aburke161 !

It has been fixed and mdoernised in the commit 53c8d53635653fab65401e90f07503162586b76b, and see the preview in KDE:

# Before

![image](https://user-images.githubusercontent.com/2257024/51783781-136e9980-2126-11e9-8e68-55c547deb21a.png)

# After

![image](https://user-images.githubusercontent.com/2257024/51783802-6c3e3200-2126-11e9-9ff1-6fa0970dc89d.png)

**Comment by gusbemacbe** [comment]
@aburke161 

Ready, official and released!

**Comment by aburke161** [comment]
@gusbemacbe 

Fantastic! Just tested on my system and can confirm it looks great. Thank you!
